[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
fetch.github = "vim-jp/vimdoc-ja"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
fetch.github = "vim-skk/skkeleton"

[skkeleton_indicator]
src.git = "https://github.com/delphinus/skkeleton_indicator.nvim"
fetch.github = "delphinus/skkeleton_indicator.nvim"
