[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
fetch.github = "vim-jp/vimdoc-ja"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
fetch.github = "vim-skk/skkeleton"

[skkeleton_indicator-nvim]
src.git = "https://github.com/N-yam-my/skkeleton_indicator.nvim"
fetch.github = "N-yam-my/skkeleton_indicator.nvim"

[vim-sonictemplate]
src.git = "https://github.com/mattn/vim-sonictemplate"
fetch.github = "mattn/vim-sonictemplate"

[denops-popup-preview-vim]
src.git = "https://github.com/matsui54/denops-popup-preview.vim"
fetch.github = "matsui54/denops-popup-preview.vim"

[ddc-source-lsp-setup]
src.git = "https://github.com/uga-rosa/ddc-source-lsp-setup"
fetch.github = "uga-rosa/ddc-source-lsp-setup"

[ddc-filter-converter_kind_labels]
src.git = "https://github.com/Shougo/ddc-filter-converter_kind_labels"
fetch.github = "Shougo/ddc-filter-converter_kind_labels"

[ddc-filter-sorter_lsp_kind]
src.git = "https://github.com/Shougo/ddc-filter-sorter_lsp_kind"
fetch.github = "Shougo/ddc-filter-sorter_lsp_kind"

[ddc-filter-matcher_prefix]
src.git = "https://github.com/Shougo/ddc-filter-matcher_prefix"
fetch.github = "Shougo/ddc-filter-matcher_prefix"

[biz-ud-mincho]
src.manual = "v1.06"
fetch.url = "https://github.com/googlefonts/morisawa-biz-ud-mincho/releases/download/v1.06/morisawa-biz-ud-mincho-fonts.zip"
