[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
fetch.github = "vim-jp/vimdoc-ja"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
fetch.github = "vim-skk/skkeleton"

[skkeleton_indicator-nvim]
src.git = "https://github.com/N-yam-my/skkeleton_indicator.nvim"
fetch.github = "N-yam-my/skkeleton_indicator.nvim"

[vim-sonictemplate]
src.git = "https://github.com/mattn/vim-sonictemplate"
fetch.github = "mattn/vim-sonictemplate"

[denops-popup-preview-vim]
src.git = "https://github.com/matsui54/denops-popup-preview.vim"
fetch.github = "matsui54/denops-popup-preview.vim"

[ddc-source-lsp-setup]
src.git = "https://github.com/uga-rosa/ddc-source-lsp-setup"
fetch.github = "uga-rosa/ddc-source-lsp-setup"
